@startuml
autonumber
LoginUI -> LoginController : login()
LoginController -> UserFaçade : login ( login:String, password : String)
UserFaçade --> DAOFactoryMySQL : new()
DAOFactoryMySQL --> UserFaçade : AbstractFactoryDAO
UserFaçade ->DAOFactoryMySQL : createUserDAO()
DAOFactoryMySQL --> UserDAOMySQL : new()
UserDAOMySQL -->UserFaçade : UserDA0
UserFaçade -> UserDAOMySQL : login(login:String, password:String)
UserDAOMySQL -> SQLConnection : createStatement()
SQLConnection --> UserDAOMySQL : true
UserDAOMySQL --> User : new()
User --> UserDAOMySQL : User
activate User
UserDAOMySQL --> UserFaçade : User
UserFaçade->UserFaçade : getInstance().setConnected(User: User)
UserFaçade --> LoginController
LoginController --> UserFaçade : isConnected()
alt successful case
    UserFaçade -> LoginController : true
    LoginController -> Router : getInstance().activate("HomePage")
else
    UserFaçade -> LoginController : false
    LoginController -> LoginController : display("Wrong combination of password and login")
end


@enduml