@startuml

class User {
    Login : String
    FirstName : String
    LastName : String
    Password : String
    EmailAddress : String
    PhoneNumber : String
    StreetAddress : String
    City : String
    PostalCode : int
    PictureUser : String
    ..
    login()
    signUp()
    updateInformation()
    searchProduct()
    consultProduct()
    seeAllCategories()
    deleteAccount()
}

class Consumer {
    ..
    setComment()
    updateComment()
    setRate()
    addProductToBasket()
    validateCommand()
    updateProductQuantityInBasket()
    deleteProductFromBasket()
    consultBasket()
    consultHistoricOrder()
    consultOrderDetails()
    consultSellerInformation()
}

class Seller {
    CompanyName
    ..
    getAverageRate()
    getComments()
    addNewProduct()
    deleteProduct()
    updateProduct()
    createProduct()
    updateOrder()
    consultHistoricOrder()
}

class Admin {
    ..
    deleteProduct()
    updateProduct()
    updateUser()
    deleteUser()
    createCategory()
    updateCategory()
    deleteCategory()
}

class Comment {
    ContentComment
    ..

}

class Product {
    nameProduct
    descriptionProduct
    priceProduct
    pictureProduct
    ..
    getAverageRate()
    getComments()
    getSeller()

    update()
    create()
    delete()
}

class Category {
    libelleCategory
    ..
}

class Order {
    quantity
    dateOrder
    deliveryDate
    deliveryAddress
    stateOrder
    ..
}

class Basket {
    quantity
    ..
    addProduct()
    createOrder()
    emptyBasket()
    changeQuantity()
    deleteProductFromBasket()
}

class Rate {
    rate
}

User <|-- Consumer
User <|-- Seller
User <|-- Admin

Consumer "0..*" --- "1..*" Product
(Consumer, Product) .. Comment

Consumer "*" --- "1" Product
(Consumer, Product) .. Rate

Consumer "1" --- "1" Seller
(Consumer, Seller) .. Rate

Product "*" --o "*" Category : Contains
Product "*" --- "1" Seller : Belongs

Order "*" --- "1" Consumer
Order "*" --- "1" Seller
Order "*" --- "*" Product

Basket "*" -- "1" Product
Basket "*" --- "1" Consumer


@enduml

//Basket "*" --- "*" Product

// parler du panier
// login / register ?
// ou mettre addProduct() ?
// obligé de faire 1 diagram par usecase ?
// où mettre searchProduct() ?