@startuml

class User {
    Login : String
    FirstName : String
    LastName : String
    Password : String
    EmailAddress : String
    PhoneNumber : String
    StreetAddress : String
    City : String
    PostalCode : int
    PictureUser : String
    ..
    login()
    signUp()
    updateInformation()
    searchProduct()
    consultProduct()
    seeAllCategories()
    deleteAccount()
}

class Consumer {
    ..
    consultBasket()
    consultHistoricOrder()
    consultOrderDetails()
    consultSellerInformation()
}

class Seller {
    CompanyName :String
    ..
    getAverageRate()
    getComments()
    consultHistoricOrder()
}

class Admin {
    ..

}

class Comment {
    ContentComment : String
    ..
    createComment()
    updateComment()
    deleteComment()
}

class Rate {
    rate : int
    ..
    createRate()
}

class Product {
    nameProduct : String
    descriptionProduct : String
    priceProduct : float
    pictureProduct : String
    ..
    getAverageRate()
    getComments()
    getSeller()
    updateProduct()
    createProduct()
    deleteProduct()
}

class Category {
    libelleCategory :String
    ..
    createCategory()
    updateCategory()
    deleteCategory()
}

class Order {
    quantity : int
    dateOrder : Date
    deliveryDate : Date
    deliveryAddress : String
    // soit celle du consumer soit du seller
    stateOrder : String
    ..
    createOrder()
    updateOrder()
}

class Basket {
    quantity : int
    ..
    addProduct()
    emptyBasket() : boolean
    changeQuantity()
    deleteProductFromBasket()
}

User <|-- Consumer
User <|-- Seller
User <|-- Admin

Consumer "*" --- "1" Product
(Consumer, Product) .. Comment

Consumer "*" --- "1" Product
(Consumer, Product) .. Rate

Consumer "1" --- "1" Seller
(Consumer, Seller) .. Rate

Product "*" --o "*" Category : Contains
Product "*" --- "1" Seller : Belongs

Order "*" --- "1" Consumer
Order "*" --- "1" Seller
Order "*" --- "*" Product

Basket "*" -- "1" Product
Basket "*" --- "1" Consumer


@enduml

//Basket "*" --- "*" Product

// parler du panier
// login / register ?
// ou mettre addProduct() ?
// obligé de faire 1 diagram par usecase ?
// où mettre searchProduct() ?